# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33136278b52e8ed060a4a0f88b11894670e1a0eb3e3de98c3d8da07197e94d2fa3c5cda0be83e772b1785b855bd99b4f5bf41790517a9a7f7980d8d0c90dc363

test:
  secret_key_base: 90a1257ffe5d674d49e3d51b7cc710e34c03f8c5e5897dd113372b6c66085aed895263e5042f0f2c267d9d77c4254b1c3d4d607793fba0d9510edd0fa2206e0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
